# Imports

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px 
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)
plt.style.use('ggplot')

# Data cleaning

In [6]:
# Import the data
df = pd.read_csv('D:/AIM-tbourbi/projet/NYPD_Complaint_Data_Historic.csv')
df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_15136\2342646575.py:2: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('D:/AIM-tbourbi/projet/NYPD_Complaint_Data_Historic.csv')

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,BORO_NM,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,JURIS_DESC,JURISDICTION_CODE,PARKS_NM,HADEVELOPT,HOUSING_PSA,X_COORD_CD,Y_COORD_CD,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,724718389,09/04/2014,17:25:00,09/04/2014,17:35:00,81.0,09/04/2014,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,BROOKLYN,OPPOSITE OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1005945.0,188862.0,NaN,NaN,NaN,NaN,40.685041,-73.921777,"(40.685040958, -73.921776995)",PATROL BORO BKLYN NORTH,NaN,25-44,WHITE,F
1,191133903,10/12/2016,07:40:00,10/12/2016,07:45:00,121.0,10/12/2016,109,GRAND LARCENY,417.0,"LARCENY,GRAND FROM PERSON,PURS",COMPLETED,FELONY,STATEN ISLAND,NaN,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,947034.0,171375.0,UNKNOWN,BLACK,U,NaN,40.636991,-74.134093,"(40.63699139, -74.134092508)",PATROL BORO STATEN ISLAND,NaN,45-64,WHITE HISPANIC,F
2,720151206,09/28/2012,13:30:00,09/28/2012,14:00:00,41.0,10/19/2012,109,GRAND LARCENY,413.0,"LARCENY,GRAND BY FALSE PROMISE",COMPLETED,FELONY,BRONX,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1014179.0,239453.0,NaN,WHITE HISPANIC,M,NaN,40.823876,-73.891863,"(40.823876276, -73.891862968)",PATROL BORO BRONX,NaN,45-64,WHITE HISPANIC,F
3,232242098,03/24/2015,15:45:00,NaN,NaN,46.0,03/24/2015,341,PETIT LARCENY,339.0,"LARCENY,PETIT FROM OPEN AREAS,",COMPLETED,MISDEMEANOR,BRONX,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1009041.0,247401.0,NaN,BLACK,M,NaN,40.845707,-73.910398,"(40.845707148, -73.910398033)",PATROL BORO BRONX,NaN,<18,WHITE HISPANIC,F
4,708078702,05/20/2017,04:02:00,05/20/2017,04:09:00,109.0,05/20/2017,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,QUEENS,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1031779.0,217663.0,25-44,WHITE HISPANIC,M,NaN,40.763992,-73.828426,"(40.763991557, -73.828425559)",PATROL BORO QUEENS NORTH,NaN,25-44,BLACK,M


**CMPLNT_NUM**	:Randomly generated persistent ID for each complaint
**CMPLNT_FR_DT**	:Exact date of occurrence for the reported event (or starting date of occurrence, if CMPLNT_TO_DT exists)
**CMPLNT_FR_TM**:Exact time of occurrence for the reported event (or starting time of occurrence, if CMPLNT_TO_TM exists)
**CMPLNT_TO_DT**:Ending date of occurrence for the reported event, if exact time of occurrence is unknown
**CMPLNT_TO_TM**:Ending time of occurrence for the reported event, if exact time of occurrence is unknown
**ADDR_PCT_CD**	:The precinct in which the incident occurred
**RPT_DT**	:Date event was reported to police
**KY_CD**:Three digit offense classification code
**OFNS_DESC**:Description of offense corresponding with key code
**PD_CD**:Three digit internal classification code (more granular than Key Code)
**PD_DESC**	:Description of internal classification corresponding with PD code (more granular than Offense Description)

**CRM_ATPT_CPTD_CD**	:Indicator of whether crime was successfully completed or attempted, but failed or was interrupted prematurely

**LAW_CAT_CD**	:Level of offense: felony, misdemeanor, violation

**BORO_NM**	:The name of the borough in which the incident occurred

**LOC_OF_OCCUR_DESC**:Specific location of occurrence in or around the premises; inside, opposite of, front of, rear of

**PREM_TYP_DESC**:Specific description of premises; grocery store, residence, street, etc.

**JURIS_DESC**	:Description of the jurisdiction code

**JURISDICTION_CODE**:Jurisdiction responsible for incident. Either internal, like Police(0), Transit(1), and Housing(2); or external(3), like Correction, Port Authority, etc.
**PARKS_NM**:Name of NYC park, playground or greenspace of occurrence, if applicable (state parks are not included)
**HADEVELOPT**:Name of NYCHA housing development of occurrence, if applicable
**HOUSING_PSA**	:Development Level Code
**X_COORD_CD**:X-coordinate for New York State Plane Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104)
**Y_COORD_CD**	:Y-coordinate for New York State Plane Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104)
**SUSP_AGE_GROUP	**:Suspect’s Age Group
**SUSP_RACE**	:Suspect’s Race Description
SUSP_SEX:Suspect’s Sex Description
**TRANSIT_DISTRICT**:Transit district in which the offense occurred.
**Latitud**e:Midblock Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)
**Longitude**:Midblock Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)
**Lat_Lon**	:Geospatial Location Point (latitude and Longitude combined)
**PATROL_BORO**	:The name of the patrol borough in which the incident occurred
**STATION_NAME**:Transit station name
**VIC_AGE_GROUP**:Victim’s Age Group
**VIC_RACE**:Victim’s Race Description
**VIC_SEX**:Victim’s Sex Description

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CMPLNT_NUM,6983207.0,5.500768e+08,2.597838e+08,1.000001e+08,3.252107e+08,5.500624e+08,7.750561e+08,9.999999e+08
ADDR_PCT_CD,6981041.0,6.327224e+01,3.451961e+01,-9.900000e+01,4.000000e+01,6.300000e+01,9.400000e+01,1.230000e+02
KY_CD,6983207.0,2.957909e+02,1.499370e+02,1.010000e+02,1.170000e+02,3.410000e+02,3.510000e+02,8.810000e+02
PD_CD,6977342.0,4.148457e+02,2.180586e+02,1.000000e+02,2.540000e+02,3.860000e+02,6.370000e+02,9.750000e+02
JURISDICTION_CODE,6977342.0,7.304343e-01,6.752324e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.700000e+01
X_COORD_CD,6959143.0,1.004796e+06,2.174732e+04,1.110000e+02,9.916830e+05,1.004370e+06,1.016586e+06,1.067298e+06
Y_COORD_CD,6959143.0,2.070544e+05,3.153994e+04,1.110000e+02,1.843520e+05,2.059660e+05,2.351580e+05,7.250292e+06
TRANSIT_DISTRICT,157084.0,1.359840e+01,1.247143e+01,1.000000e+00,3.000000e+00,1.100000e+01,3.000000e+01,3.400000e+01
Latitude,6959143.0,4.073495e+01,8.647664e-02,4.011271e+01,4.067261e+01,4.073196e+01,4.081212e+01,5.965727e+01
Longitude,6959143.0,-7.392583e+01,7.842862e-02,-7.751921e+01,-7.397323e+01,-7.392733e+01,-7.388325e+01,-7.368479e+01

In [ ]:
# drop useless columns
df.drop(columns = ['PD_CD','PD_DESC','JURISDICTION_CODE','JURIS_DESC','KY_CD','RPT_DT','LOC_OF_OCCUR_DESC'],inplace = True)

In [9]:
# percentage of nan values for each column
for column in df.columns:
    print(f'{column}:missing {df[column].isna().sum()*100/len(df)}')

CMPLNT_NUM:missing 0.0
CMPLNT_FR_DT:missing 0.009379644624597266
CMPLNT_FR_TM:missing 0.0006873632701994943
CMPLNT_TO_DT:missing 23.89125798504899
CMPLNT_TO_TM:missing 23.826144635265717
ADDR_PCT_CD:missing 0.03101726756775218
OFNS_DESC:missing 0.26957528253136415
CRM_ATPT_CPTD_CD:missing 0.00010024047690409292
LAW_CAT_CD:missing 0.0
BORO_NM:missing 0.1560028221990269
PREM_TYP_DESC:missing 0.5689649469076314
PARKS_NM:missing 99.6413109335009
HADEVELOPT:missing 95.04485546540437
HOUSING_PSA:missing 92.31142654084292
X_COORD_CD:missing 0.3445981194600131
Y_COORD_CD:missing 0.3445981194600131
SUSP_AGE_GROUP:missing 67.41276608297592
SUSP_RACE:missing 47.81516572543246
SUSP_SEX:missing 49.72423128800278
TRANSIT_DISTRICT:missing 97.75054641799964
Latitude:missing 0.3445981194600131
Longitude:missing 0.3445981194600131
Lat_Lon:missing 0.3445981194600131
PATROL_BORO:missing 0.09053147071252506
STATION_NAME:missing 97.75054641799964
VIC_AGE_GROUP:missing 23.46262970580709
VIC_RACE:missing 0.0044105809837800885
VIC_SEX:missing 0.004396260915650933

TRANSIT_DISTRICT and HOUSING_PSA ,HADEVELOPT, STATION_NAME have  the most high missing values

In [ ]:
# drop columns with high nan and redundent information %
df.drop(columns=['HOUSING_PSA','TRANSIT_DISTRICT'],inplace=True)

In [11]:
df.loc[df['PARKS_NM'].notnull(),'PARKS_NM'] = 1
df.loc[df['PARKS_NM'].isna(),'PARKS_NM'] = 0

df.loc[df['HADEVELOPT'].notnull(),'HADEVELOPT'] = 1
df.loc[df['HADEVELOPT'].isna(),'HADEVELOPT'] = 0

df.loc[df['STATION_NAME'].notnull(),'STATION_NAME'] = 1
df.loc[df['STATION_NAME'].isna(),'STATION_NAME'] = 0


df = df.rename({'PARKS_NM':'IN_PARK','HADEVELOPT':'IN_PUBLIC_HOUSING','STATION_NAME':'IN_STATION'},axis = 1)

In [12]:
#remove unnecessary coordinate columns
df.drop(columns=['X_COORD_CD','Y_COORD_CD',"Lat_Lon"],inplace=True)

In [13]:
# Rows without coordinates should be dropped
df = df[df['Latitude'].notna()]
df = df[df['Longitude'].notna()]

In [14]:
# check if the two columns have the same values
if all(df['CMPLNT_FR_DT'].notna() == df['CMPLNT_TO_DT'].notna()):
    df.drop(columns='CMPLNT_TO_DT',inplace = True)

In [19]:
# change date columns to YYYY-MM-DD
df['CMPLNT_FR_DT']= pd.to_datetime(df['CMPLNT_FR_DT'],errors='coerce')
df['CMPLNT_FR_TM'] = pd.to_datetime(df['CMPLNT_FR_TM'],errors='coerce')

C:\Users\HP\AppData\Local\Temp\ipykernel_15136\2903593181.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['CMPLNT_FR_TM'] = pd.to_datetime(df['CMPLNT_FR_TM'],errors='coerce')

In [20]:
df.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,OFNS_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,IN_PARK,IN_PUBLIC_HOUSING,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,Latitude,Longitude,PATROL_BORO,IN_STATION,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,724718389,2014-09-04,2023-12-28 17:25:00,09/04/2014,17:35:00,81.0,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,BROOKLYN,STREET,0,0,NaN,NaN,NaN,40.685041,-73.921777,PATROL BORO BKLYN NORTH,0,25-44,WHITE,F
1,191133903,2016-10-12,2023-12-28 07:40:00,10/12/2016,07:45:00,121.0,GRAND LARCENY,COMPLETED,FELONY,STATEN ISLAND,STREET,0,0,UNKNOWN,BLACK,U,40.636991,-74.134093,PATROL BORO STATEN ISLAND,0,45-64,WHITE HISPANIC,F
2,720151206,2012-09-28,2023-12-28 13:30:00,09/28/2012,14:00:00,41.0,GRAND LARCENY,COMPLETED,FELONY,BRONX,STREET,0,0,NaN,WHITE HISPANIC,M,40.823876,-73.891863,PATROL BORO BRONX,0,45-64,WHITE HISPANIC,F
3,232242098,2015-03-24,2023-12-28 15:45:00,NaN,NaN,46.0,PETIT LARCENY,COMPLETED,MISDEMEANOR,BRONX,STREET,0,0,NaN,BLACK,M,40.845707,-73.910398,PATROL BORO BRONX,0,<18,WHITE HISPANIC,F
4,708078702,2017-05-20,2023-12-28 04:02:00,05/20/2017,04:09:00,109.0,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,QUEENS,STREET,0,0,25-44,WHITE HISPANIC,M,40.763992,-73.828426,PATROL BORO QUEENS NORTH,0,25-44,BLACK,M

In [21]:
# delete columns that have no event start date or time
df = df[df['CMPLNT_FR_DT'].notna()]
df = df[df['CMPLNT_FR_TM'].notna()]

In [22]:
# these columns have redundent info
df.drop(columns='CMPLNT_TO_TM',inplace = True)
df.drop(columns='CMPLNT_TO_DT',inplace = True)

In [23]:
# split date to year, month and day
df['year'] = df['CMPLNT_FR_DT'].dt.year
df['month'] = df['CMPLNT_FR_DT'].dt.month
df['day'] = df['CMPLNT_FR_DT'].dt.day
df['hour'] =df['CMPLNT_FR_TM'].dt.hour
# add week day column
df['weekday'] = pd.to_datetime(df['CMPLNT_FR_DT']).dt.day_name()
df.drop(columns='CMPLNT_FR_DT',inplace = True)
df.drop(columns='CMPLNT_FR_TM',inplace = True)

In [24]:
df.head()

,CMPLNT_NUM,ADDR_PCT_CD,OFNS_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,IN_PARK,IN_PUBLIC_HOUSING,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,Latitude,Longitude,PATROL_BORO,IN_STATION,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,year,month,day,hour,weekday
0,724718389,81.0,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,BROOKLYN,STREET,0,0,NaN,NaN,NaN,40.685041,-73.921777,PATROL BORO BKLYN NORTH,0,25-44,WHITE,F,2014,9,4,17,Thursday
1,191133903,121.0,GRAND LARCENY,COMPLETED,FELONY,STATEN ISLAND,STREET,0,0,UNKNOWN,BLACK,U,40.636991,-74.134093,PATROL BORO STATEN ISLAND,0,45-64,WHITE HISPANIC,F,2016,10,12,7,Wednesday
2,720151206,41.0,GRAND LARCENY,COMPLETED,FELONY,BRONX,STREET,0,0,NaN,WHITE HISPANIC,M,40.823876,-73.891863,PATROL BORO BRONX,0,45-64,WHITE HISPANIC,F,2012,9,28,13,Friday
3,232242098,46.0,PETIT LARCENY,COMPLETED,MISDEMEANOR,BRONX,STREET,0,0,NaN,BLACK,M,40.845707,-73.910398,PATROL BORO BRONX,0,<18,WHITE HISPANIC,F,2015,3,24,15,Tuesday
4,708078702,109.0,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,QUEENS,STREET,0,0,25-44,WHITE HISPANIC,M,40.763992,-73.828426,PATROL BORO QUEENS NORTH,0,25-44,BLACK,M,2017,5,20,4,Saturday

In [25]:
# clean suspect and victim data
df['SUSP_RACE'] = df['SUSP_RACE'].fillna('UNKNOWN')
df['VIC_RACE'] = df['VIC_RACE'].fillna('UNKNOWN')

df['SUSP_SEX'] = df['SUSP_SEX'].fillna('U')
df['VIC_SEX'] = df['VIC_SEX'].fillna('U')

In [26]:
# take care of unvalid age data
valid_age = ['UNKNOWN', '25-44', '<18', '45-64', '65+', '18-24']
df.loc[~df['SUSP_AGE_GROUP'].isin(valid_age),'SUSP_AGE_GROUP'] = 'UNKNOWN'
df.loc[~df['VIC_AGE_GROUP'].isin(valid_age),'VIC_AGE_GROUP'] = 'UNKNOWN'

In [27]:
# redundent data
df.drop(columns='PATROL_BORO',inplace = True)
df['BORO_NM'] = df['BORO_NM'].fillna('UNKNOWN')

In [28]:
df.head()

,CMPLNT_NUM,ADDR_PCT_CD,OFNS_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,IN_PARK,IN_PUBLIC_HOUSING,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,Latitude,Longitude,IN_STATION,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,year,month,day,hour,weekday
0,724718389,81.0,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,BROOKLYN,STREET,0,0,UNKNOWN,UNKNOWN,U,40.685041,-73.921777,0,25-44,WHITE,F,2014,9,4,17,Thursday
1,191133903,121.0,GRAND LARCENY,COMPLETED,FELONY,STATEN ISLAND,STREET,0,0,UNKNOWN,BLACK,U,40.636991,-74.134093,0,45-64,WHITE HISPANIC,F,2016,10,12,7,Wednesday
2,720151206,41.0,GRAND LARCENY,COMPLETED,FELONY,BRONX,STREET,0,0,UNKNOWN,WHITE HISPANIC,M,40.823876,-73.891863,0,45-64,WHITE HISPANIC,F,2012,9,28,13,Friday
3,232242098,46.0,PETIT LARCENY,COMPLETED,MISDEMEANOR,BRONX,STREET,0,0,UNKNOWN,BLACK,M,40.845707,-73.910398,0,<18,WHITE HISPANIC,F,2015,3,24,15,Tuesday
4,708078702,109.0,ASSAULT 3 & RELATED OFFENSES,COMPLETED,MISDEMEANOR,QUEENS,STREET,0,0,25-44,WHITE HISPANIC,M,40.763992,-73.828426,0,25-44,BLACK,M,2017,5,20,4,Saturday

In [29]:
df.dropna(inplace=True)
len(df)

6901168

In [30]:
# encode crime severity
df['LAW_CAT_CD'] = df['LAW_CAT_CD'].replace(['felony','misdemeanor','violation'],[2,1,0])

In [31]:
df.columns

Index(['CMPLNT_NUM', 'ADDR_PCT_CD', 'OFNS_DESC', 'CRM_ATPT_CPTD_CD',
       'LAW_CAT_CD', 'BORO_NM', 'PREM_TYP_DESC', 'IN_PARK',
       'IN_PUBLIC_HOUSING', 'SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX',
       'Latitude', 'Longitude', 'IN_STATION', 'VIC_AGE_GROUP', 'VIC_RACE',
       'VIC_SEX', 'year', 'month', 'day', 'hour', 'weekday'],
      dtype='object')

Rename the LAW_CAT_CD colomn to a more meanigful name

In [32]:

df = df.rename({'LAW_CAT_CD':'CRIME_CLASS'},axis = 1)

In [33]:
df['CRIME_CLASS'].value_counts()

CRIME_CLASS
MISDEMEANOR    3888210
FELONY         2124247
VIOLATION       888711
Name: count, dtype: int64

In [36]:
#reorder the dataframe
column_titles = ['CMPLNT_NUM','year','month', 'day','weekday','hour','Latitude', 'Longitude', 'CRM_ATPT_CPTD_CD',
                 'OFNS_DESC', 'ADDR_PCT_CD', 'CRIME_CLASS', 'BORO_NM', 'PREM_TYP_DESC',
                 'IN_PARK', 'IN_PUBLIC_HOUSING', 'IN_STATION',
                 'SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX',
                 'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX']
df = df.reindex(columns = column_titles)

In [37]:
df.head()

,CMPLNT_NUM,year,month,day,weekday,hour,Latitude,Longitude,CRM_ATPT_CPTD_CD,OFNS_DESC,ADDR_PCT_CD,CRIME_CLASS,BORO_NM,PREM_TYP_DESC,IN_PARK,IN_PUBLIC_HOUSING,IN_STATION,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,724718389,2014,9,4,Thursday,17,40.685041,-73.921777,COMPLETED,ASSAULT 3 & RELATED OFFENSES,81.0,MISDEMEANOR,BROOKLYN,STREET,0,0,0,UNKNOWN,UNKNOWN,U,25-44,WHITE,F
1,191133903,2016,10,12,Wednesday,7,40.636991,-74.134093,COMPLETED,GRAND LARCENY,121.0,FELONY,STATEN ISLAND,STREET,0,0,0,UNKNOWN,BLACK,U,45-64,WHITE HISPANIC,F
2,720151206,2012,9,28,Friday,13,40.823876,-73.891863,COMPLETED,GRAND LARCENY,41.0,FELONY,BRONX,STREET,0,0,0,UNKNOWN,WHITE HISPANIC,M,45-64,WHITE HISPANIC,F
3,232242098,2015,3,24,Tuesday,15,40.845707,-73.910398,COMPLETED,PETIT LARCENY,46.0,MISDEMEANOR,BRONX,STREET,0,0,0,UNKNOWN,BLACK,M,<18,WHITE HISPANIC,F
4,708078702,2017,5,20,Saturday,4,40.763992,-73.828426,COMPLETED,ASSAULT 3 & RELATED OFFENSES,109.0,MISDEMEANOR,QUEENS,STREET,0,0,0,25-44,WHITE HISPANIC,M,25-44,BLACK,M

In [38]:
df = df[df['year']>2005]
df_2019 = df[df['year']==2019]
df_train = df[df['year']!=2019]

In [39]:
df.to_csv('ny_clean_all.csv',index= False)
df_train.to_csv('ny_clean.csv',index=False)
df_2019.to_csv('ny_clean_2019.csv',index=False)